version: '3.3'

services:
   surge:
      build:
        dockerfile: ./Dockerfile
        context: .
      container_name: surge
      restart: always
      env_file:
        - ./settings.env
      ports:
        - "8003:8000"
      command: ["uwsgi", "--callable", "application", "--wsgi-file", "./surge/wsgi.py", "--processes=2", "--protocol=http", "-b 32768" ,  "--wsgi-disable-file-wrapper", "--socket-timeout=120"]
      networks:
        - surge-network

   surge-cronjob:
     build:
       dockerfile: ./Dockerfile
       context: .
     container_name: surge-cronjob
     restart: always
     env_file:
       - ./settings.env
     ports:
       - "8002:8000"
     command: ["worker" , "-A" , "surge" , "-B" , "--loglevel=info"]
     networks:
       - surge-network

   postgres:
     image: "postgis/postgis:13-master"
     container_name: postgress
     env_file:
       - ./postgis.env
     ports:
       - "5434:5432"
     volumes:
       - postgres-data:/var/lib/postgresql/data/
     networks:
       - surge-network

   redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server
    ports:
       - "6381:6379"
    volumes:
       - redis-data:/data
    environment:
       - REDIS_REPLICATION_MODE=master
    networks:
       - surge-network

networks:
  surge-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: