version: '3.3'

services:
   surge:
      build:
        dockerfile: ./Dockerfile
        context: .
      container_name: surge
      restart: always
      env_file:
        - ./settings.env
      ports:
        - "8000:8000"
      command: ["uwsgi", "--callable", "application", "--wsgi-file", "./user/wsgi.py", "--processes=4", "--protocol=http", "-b 32768" ,  "--wsgi-disable-file-wrapper", "--socket-timeout=120"]
      networks:
        - surge-network


   surge-cronjob:
     build:
       dockerfile: ./Dockerfile
       context: .
     container_name: surge-cronjob
     restart: always
     env_file:
       - ./settings.env
     ports:
       - "8000:8000"
     command: ["worker" , "-A" , "surge" , "-B" , "--loglevel=info"]
     networks:
       - surge-network


   postgres:
     image: "postgis/postgis:13-master"
     env_file:
       - .env
     ports:
       - "5432:5432"
     volumes:
       - db-data:/var/lib/postgresql/data/
     networks:
       - surge-network


networks:
  sruge-network:
    driver: bridge

volumes:
  db-data: