# Generated by Django 3.2 on 2021-12-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('district', models.PositiveSmallIntegerField(db_index=True, verbose_name='District')),
                ('requested_time', models.DateTimeField(db_index=True, verbose_name='Requested Time')),
                ('requested_count', models.PositiveBigIntegerField(verbose_name='Requested Count')),
            ],
            options={
                'db_table': 'request_district',
            },
        ),
    ]
