# Generated by Django 3.2 on 2021-12-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('request_count', models.PositiveBigIntegerField(unique=True, verbose_name='Request Count')),
                ('coefficient', models.FloatField(verbose_name='Coefficient')),
            ],
            options={
                'db_table': 'threshold',
            },
        ),
    ]
